name: famedly_dart_lints
version: 1.0.0
description: Default linting rules for Famedly Dart projects
homepage: https://famedly.com
repository: https://github.com/famedly/frontend-ci-templates
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  dart_code_linter: ^3.2.1
  lints: ^6.1.0